HHH-17594 Here a test case with the expected error
org.hibernate.InstantiationException: Could not instantiate entity 'org.hibernate.bugs.entities.relation.AddressUserRelationId' due to: Could not set value of type [org.hibernate.bugs.entities.address.Address]: 'org.hibernate.bugs.entities.relation.AddressUserRelationId.myAddress' (setter)